# Use the official Golang image as the base image for the build stage
FROM golang:1.20

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY go.mod .
COPY client.go .

# Build the Go app
RUN go build -o client

# Command to run the executable
ENTRYPOINT ["/app/client"]
