
# Use the official Golang image as the base image for the build stage
FROM golang:1.20

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY go.mod .
copy account-manager.go .

# Build the Go app
RUN go build -o account-manager


# Create the storage directory
RUN mkdir -p /app/storage

# Command to run the executable
ENTRYPOINT ["/app/account-manager"]

