# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-management
  template:
    metadata:
      labels:
        app: account-management
    spec:
      containers:
      - name: account-manager
        image: account-manager:latest
        ports:
        - containerPort: 8080
      - name: client1
        image: client:latest
      - name: client2
        image: client:latest
---
apiVersion: v1
kind: Service
metadata:
  name: account-manager-service
spec:
  selector:
    app: account-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
