# Use the official Golang image as the base image for the build stage
FROM golang:1.20

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY go.mod .
COPY accounts-monitor.go .
COPY ./public /app/public

# Build the Go app
RUN go build -o accounts-monitor .

# Command to run the executable
ENTRYPOINT ["/app/accounts-monitor"]